// Code generated by protoc-gen-go.
// source: protos/fn.proto
// DO NOT EDIT!

/*
Package fn is a generated protocol buffer package.

It is generated from these files:
	protos/fn.proto

It has these top-level messages:
	ListFunctionsReply
	Function
	DeployFunctionRequest
	DeleteFunctionRequest
*/
package fn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListFunctionsReply struct {
	Functions []*Function `protobuf:"bytes,1,rep,name=functions" json:"functions,omitempty"`
}

func (m *ListFunctionsReply) Reset()                    { *m = ListFunctionsReply{} }
func (m *ListFunctionsReply) String() string            { return proto.CompactTextString(m) }
func (*ListFunctionsReply) ProtoMessage()               {}
func (*ListFunctionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListFunctionsReply) GetFunctions() []*Function {
	if m != nil {
		return m.Functions
	}
	return nil
}

type Function struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Output only.
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Function) Reset()                    { *m = Function{} }
func (m *Function) String() string            { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()               {}
func (*Function) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Function) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type DeployFunctionRequest struct {
	Function *Function `protobuf:"bytes,1,opt,name=function" json:"function,omitempty"`
}

func (m *DeployFunctionRequest) Reset()                    { *m = DeployFunctionRequest{} }
func (m *DeployFunctionRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployFunctionRequest) ProtoMessage()               {}
func (*DeployFunctionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeployFunctionRequest) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

type DeleteFunctionRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteFunctionRequest) Reset()                    { *m = DeleteFunctionRequest{} }
func (m *DeleteFunctionRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFunctionRequest) ProtoMessage()               {}
func (*DeleteFunctionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*ListFunctionsReply)(nil), "fn.ListFunctionsReply")
	proto.RegisterType((*Function)(nil), "fn.Function")
	proto.RegisterType((*DeployFunctionRequest)(nil), "fn.DeployFunctionRequest")
	proto.RegisterType((*DeleteFunctionRequest)(nil), "fn.DeleteFunctionRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Fn service

type FnClient interface {
	ListFunctions(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ListFunctionsReply, error)
	DeployFunction(ctx context.Context, in *DeployFunctionRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	DeleteFunction(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type fnClient struct {
	cc *grpc.ClientConn
}

func NewFnClient(cc *grpc.ClientConn) FnClient {
	return &fnClient{cc}
}

func (c *fnClient) ListFunctions(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ListFunctionsReply, error) {
	out := new(ListFunctionsReply)
	err := grpc.Invoke(ctx, "/fn.Fn/ListFunctions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fnClient) DeployFunction(ctx context.Context, in *DeployFunctionRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/fn.Fn/DeployFunction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fnClient) DeleteFunction(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/fn.Fn/DeleteFunction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fn service

type FnServer interface {
	ListFunctions(context.Context, *google_protobuf.Empty) (*ListFunctionsReply, error)
	DeployFunction(context.Context, *DeployFunctionRequest) (*google_protobuf.Empty, error)
	DeleteFunction(context.Context, *DeleteFunctionRequest) (*google_protobuf.Empty, error)
}

func RegisterFnServer(s *grpc.Server, srv FnServer) {
	s.RegisterService(&_Fn_serviceDesc, srv)
}

func _Fn_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FnServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fn.Fn/ListFunctions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FnServer).ListFunctions(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fn_DeployFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FnServer).DeployFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fn.Fn/DeployFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FnServer).DeployFunction(ctx, req.(*DeployFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fn_DeleteFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FnServer).DeleteFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fn.Fn/DeleteFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FnServer).DeleteFunction(ctx, req.(*DeleteFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fn.Fn",
	HandlerType: (*FnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFunctions",
			Handler:    _Fn_ListFunctions_Handler,
		},
		{
			MethodName: "DeployFunction",
			Handler:    _Fn_DeployFunction_Handler,
		},
		{
			MethodName: "DeleteFunction",
			Handler:    _Fn_DeleteFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protos/fn.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x2d, 0x1a, 0x53, 0xa6, 0xfe, 0x49, 0x26, 0xb1, 0xa9, 0x78, 0xd0, 0x70, 0x22, 0x9a,
	0x40, 0x82, 0x27, 0x6f, 0x92, 0xd8, 0x9e, 0x3c, 0x11, 0x2f, 0x9e, 0x0c, 0xad, 0x43, 0x43, 0x02,
	0xbb, 0x58, 0x86, 0x03, 0x1f, 0xd4, 0xef, 0xe3, 0xb2, 0xb8, 0xd5, 0x52, 0x7a, 0xdb, 0xcc, 0x7b,
	0xfb, 0xde, 0x6f, 0x06, 0x2e, 0xcb, 0x8d, 0x64, 0x59, 0x05, 0xa9, 0xf0, 0xf5, 0x0b, 0xad, 0x54,
	0x38, 0x37, 0x6b, 0x29, 0xd7, 0x39, 0x05, 0x7a, 0xb2, 0xac, 0xd3, 0x80, 0x8a, 0x92, 0x9b, 0xce,
	0xe0, 0xdc, 0xf6, 0x45, 0xce, 0x0a, 0xaa, 0x38, 0x29, 0xca, 0xce, 0xe0, 0x3e, 0x03, 0xbe, 0x66,
	0x15, 0x2f, 0x6a, 0xb1, 0xe2, 0x4c, 0x8a, 0x2a, 0xa6, 0x32, 0x6f, 0xf0, 0x1e, 0xec, 0xd4, 0x4c,
	0x66, 0xa3, 0xbb, 0x63, 0x6f, 0x12, 0x9e, 0xf9, 0xaa, 0xd5, 0xd8, 0xe2, 0x3f, 0xd9, 0x7d, 0x87,
	0xb1, 0x19, 0x23, 0xc2, 0x89, 0x48, 0x0a, 0x52, 0x5f, 0x46, 0x9e, 0x1d, 0xeb, 0x37, 0x3e, 0x01,
	0xac, 0x36, 0x94, 0x30, 0x7d, 0x7e, 0x24, 0x3c, 0xb3, 0x94, 0x32, 0x09, 0x1d, 0xbf, 0xe3, 0xf2,
	0x0d, 0x97, 0xff, 0x66, 0xb8, 0x62, 0xfb, 0xd7, 0x1d, 0xb1, 0x1b, 0xc1, 0xd5, 0x8b, 0xe2, 0x91,
	0xcd, 0xb6, 0x97, 0xbe, 0x6a, 0x65, 0x43, 0x0f, 0xc6, 0x06, 0x40, 0x77, 0xf5, 0xf1, 0xb6, 0xaa,
	0xfb, 0xd0, 0x46, 0xe4, 0xc4, 0xd4, 0x8f, 0x18, 0x40, 0x0d, 0xbf, 0x47, 0x60, 0x2d, 0x04, 0x46,
	0x70, 0xbe, 0x73, 0x13, 0x9c, 0xee, 0xe1, 0xce, 0xdb, 0x1b, 0x3b, 0xd3, 0xb6, 0x74, 0xff, 0x7c,
	0xee, 0x11, 0xce, 0xe1, 0x62, 0x97, 0x1c, 0xaf, 0x5b, 0xef, 0xe0, 0x36, 0xce, 0x81, 0x78, 0x13,
	0xf3, 0x9f, 0xde, 0xc4, 0x0c, 0x6c, 0x74, 0x38, 0x66, 0x79, 0xaa, 0x27, 0x8f, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xa6, 0x72, 0xa6, 0xcd, 0x40, 0x02, 0x00, 0x00,
}
