
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fnapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fnapi
    spec:
      containers:
      - name: fnapi
        image: localhost:5000/fnapi
        ports:
        - containerPort: 50050
          name: grpc
        env:
        - name: DATABASE_ADDRESS
          value: rethinkdb
