
kind: Service
apiVersion: v1
metadata:
  name: fnapi
spec:
  selector:
    app: fnapi
  ports:
  - port: 50050
    targetPort: 50050
    name: grpc
  - port: 8080
    targetPort: 8080
    name: http
  type: LoadBalancer
