
kind: Service
apiVersion: v1
metadata:
  name: rethinkdb
spec:
  selector:
    app: rethinkdb
  ports:
  - port: 8080
    targetPort: 8080
    name: panel
  - port: 28015
    targetPort: 28015
    name: api
  type: LoadBalancer
