
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rethinkdb
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rethinkdb
    spec:
      containers:
      - name: rethinkdb
        image: rethinkdb:2.3
        ports:
        - containerPort: 8080
          name: admin
        - containerPort: 28015
          name: api
